/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomInput: typeof import('./src/components/CustomInput.vue')['default']
    CustomList: typeof import('./src/components/CustomList.vue')['default']
    CustomTilte: typeof import('./src/components/CustomTilte.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
